lua/wire/client/hlzasm/hc_codetree.lua

Solves #10
Could use a more thorough look by someone with more time but as far as my tests indicate, this solves the issue with no side effects
Original Code:
Before fix:
After fix:
Extra example:

Carry segments over during complex memory access expressions

---

lua/wire/client/hlzasm/hc_codetree.lua
lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_expression.lua
lua/wire/client/hlzasm/hc_output.lua
lua/wire/client/hlzasm/hc_preprocess.lua
lua/wire/client/hlzasm/hc_syntax.lua

Solves #9
Changes can be separated if desired by maintainers.
NOTE this does NOT affect default behavior, all registers past EDI default to busy so code generation WILL NOT BE AFFECTED unless you EXPLICITLY USE THESE FEATURES, thank you.
All features are showcased & tested in this code snippet
(generated code)
Register variables can now be zapped, this will free the register and gives an error message if the variable is referenced on later lines in the function
example of said errors:
Changes the default state of the compiler to have the range between the two registers all zapped or preserved by default on all leaves, each preserve/zap is processed in order, for example:
`#pragma preserve EAX,EBP`
`#pragma zap EBX,EDX`
will leave EBX,ECX,EDX zapped but the others in the range of EAX,EBP …

Zap register variables and R0-31, zap/preserve entire ranges, global zap/preserve

---

lua/wire/cpulib.lua
lua/wire/zvm/zvm_features.lua
lua/wire/zvm/zvm_opcodes.lua

Adds two new instructions
STERR (X),(Y) and CLERR
STERR(opcode 150) sets the CPU error output in a similar manner to actual errors, where X is the error code(equivalent to LINT) and Y is the error parameter(equivalent to LADD), but doesn't trigger an interrupt or set LINT/LADD on use, for example:
`STERR 1,65536` would display 1.065536 as the error from the CPU
CLERR(opcode 151) sets the CPU error to 0 without resetting the actual CPU, but doesn't change the LINT/LADD registers internally(they can be changed via CPUSET anyway)
This is primarily aimed at users who want to display custom error codes, or those who would like to clear the error from the CPU on successfully handled errors/interrupts, like the ones that may frequently occur through hardware signalling with external interrupts.

Instructions for setting the cpu error or clearing it in programs

---

lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_preprocess.lua
lua/wire/client/hlzasm/hc_tokenizer.lua

Solves #8
Allows smarter preprocessing, including the branching of ifdefs and conditional pragmas/macros, not just conditional instructions, with the addition of a new pragma to turn this behavior on and off named **NewIfDefs**
**This will default to ON**, use `#pragma set NewIfDefs false` to turn it off if you still need the old behaviors to compile (if desired by maintainers and/or community this can be set to default OFF)
Example of skipping the `#ifdef y` that's in the failed `#ifdef x`, resulting in a size of 12 bytes for the compiled code
Note that the old version, would also parse the `#ifdef y` that's wrapped in `#ifdef x` even if `x` isn't defined, which accounts for the 2 byte size increase(to 14 bytes)
Example w/ all tested cases for the result of the two numbers & the name of …

Failed ifdefs now stop processing macros inside of them

---

lua/wire/client/hlzasm/hc_codetree.lua

Fixes #2
It still behaves a bit weirdly in my opinion (I haven't actually used this operator much) but this should make it stop converting label constants to nil valued and unnamed addresses for the *operator
Example showing its behavior, wrapping the label expression in parenthesis will modify the read position, where without parenthesis it will read the value at [label] and then modify the value in the temp register

Fixes Dereferencing ASM labels using the prefix * operator

---

lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_preprocess.lua
lua/wire/client/hlzasm/hc_tokenizer.lua
lua/wire/cpulib.lua

Quite frankly this was an overdue addition, as up to this point most users may not have ever known that warnings were in the console, this provides a quick and easy way to jump to said warnings, and makes the addition of new warnings more meaningful from here on out since everyone will see them(unless they use the handy dandy pragma commands I've added to silence them)
Displays filename for includes with warnings in them
Furthermore, included file warnings are accurate to where the warning is in the included file, though you can't automatically jump into the file by double clicking on external file warnings, you can jump to the line/col if you open the file manually
Additionally, you can silence editor warnings on a per-file basis using
`#pragma silence self` - Mutes warnings generated by …

ZCPU Compile-time warnings can now be displayed in the editor + pragma for muting them

---

lua/wire/client/hlzasm/hc_preprocess.lua

I forgot to remove them, didn't realize they were still in until I tested #14 with #16 enabled at the same time.
Trying to give them a proper position(other than 1:1) results in wildly inaccurate line/col numbers, so I'm just removing the warn altogether because they're annoying (I would sincerely hope that users won't need these in the first place)

Removes failed ifdef "skipping to next macro" warning

---

lua/wire/client/hlzasm/hc_codetree.lua
lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_expression.lua
lua/wire/client/hlzasm/hc_output.lua
lua/wire/client/hlzasm/hc_syntax.lua

Solves part of #4, as this PR doesn't touch array access
Partially adds compiler support for what I'm calling "large variables" for the moment, you can explicit assign a large variable of the same size to another large variable to copy all of its parameters to the left hand, as well, putting large variables as parameters for a function now pushes x number of bytes to the stack
Functions that return large variables will return a pointer to the variable, and assignment to another large variable generates a constant number of mov and inc instructions to fill the large variable on the left hand
Currently "large variables" only encompass structs, but hopefully I've left things flexible enough for future expansion (not that I really know what else to add past this)
See image for working code …

Structs can now pass into and be returned from functions + Easy struct reassignment

---

lua/wire/client/hlzasm/hc_syntax.lua
lua/wire/client/hlzasm/hc_tokenizer.lua

Example of what this is solving:
Latest commit also fixes high-level register usage near zaps/preserves
Makes zap/preserve checks check for a colon or any operator coming immediately after the IDENT/Register token, if present, breaks out of zap/preserve logic and restarts statement parsing from the ident/register token's position

Zap/Preserve now ignores variables/identifiers that are unrelated

---

lua/entities/gmod_wire_gpu/cl_init.lua

Old hud GPU behavior
https://github.com/wiremod/wire-cpu/assets/57756830/2a3f310c-ab13-4c64-b9c9-97fad16b1bee
Fixed hud GPU behavior
https://github.com/wiremod/wire-cpu/assets/57756830/cbf9ad51-ced3-489c-b434-586388babdfc

Force GPU to always render if on hud 

---

lua/wire/zvm/zvm_features.lua

In the code for the interrupt handler, there is a small table of what the interrupt flags should do
```
--Flags:
--3  [8 ] = CMPR shows if interrupt occured
--4  [16] = Interrupt does not set CS
--5  [32] = Interrupt enabled
--6  [64] = NMI interrupt
--7  [128] = Replace PTBL with NewPTE (overrides #8)
--8  [256] = Replace PTBE with NewPTE
--9  [512] = Push extended registers (R0-R31)
```
This brings interrupt flag 8, (Replace page table entries with page table byte from interrupt descriptor) closer to what the comment implies it should do, due to a possible mistake in the original implementation in [this commit](https://github.com/wiremod/wire/commit/151f9526835ba1ac0b6869998f5d5acc4ad015b6) and [this second commit claiming to fix …

Correct INT Flag 8 to set page table entries to the correct value rather than 1

---

data/cpuchip/examples/interrupts.txt
data/cpuchip/examples/segments.txt
data/cpuchip/examples/stack_setup.txt

Includes three new CPU examples, which show working code, detailing the following;
interrupts.txt: Loading an Interrupt table with an external, internal, and a timer called interrupt, to print three separate strings to a console screen
segments.txt: Segment theory & use, as well as an example of running user code from the membus as if it were on the CPU itself
stack_setup.txt: Setting up a stack by setting the stack registers(segment,size,pointer), and using it in a practical example to push a hello world to a console screen
If I made any mistakes, or if there's a clearer way to word these concepts, let me know and I can correct the files.

ZCPU examples for interrupts, segments, and stack

---

lua/wire/zvm/zvm_core.lua
lua/wire/zvm/zvm_opcodes.lua

Currently from the main branch after #27, attempting to use the INT, SPG, CPG, SPP, CPP, SRL, and SMAP instructions may cause a lua error, relating to string.format of Dyn_EmitInterrupt expecting both arguments to be numbers(how naive of me)
In the case of INT, because it passes the string $1(macro for first operand of the instruction, which hasn't been replaced with the final name yet) to Dyn_EmitInterrupt()
In the case of the paging instructions listed, because they pass the string IDX as second argument to Dyn_EmitInterrupt().

Fix emits killing lua on emitted interrupt

---

lua/wire/client/hlzasm/hc_syntax.lua

I accidentally closed the previous pr by deleting the branch, whoops!
Compiler can now handle an arbitrary ptr level for functions, where it previously died on ptr types due to #17 making function generation check its own type, which did not account for ptr types, as they're handled as separate tokens.

Fix returning ptr types from functions

---

lua/wire/zvm/zvm_opcodes.lua

Got broken by me during #27 because I forgot Dyn_EmitOperand was non formatting, also fixes #39 (the SPU examples needed TIMER to function properly)

Fix TIMER instruction

---

data/spuchip/examples/mario_theme.txt

Turns out the code for the tempo control only ran between notes 120 and 230, the tempo(864) was ignored because there were no curly braces, which explains the garbled mess of notes at the beginning and end.
Comparison video
https://github.com/wiremod/wire-cpu/assets/57756830/b3875325-a76a-4fc6-93c9-a817623f267b
If #33 passes before this I'll change the folder to data_static, else I'll update #33 to have this change in the proper folder

Correct the mario_theme example for SPU

---

lua/wire/client/hlzasm/hc_preprocess.lua

#else decrementing the number of ifdefs to skip can cause it to break out early and parse one too many endifs, breaking the compiler.
Consider the following:
```
// x is undefined
// y can be defined or undefined while still causing the error
#ifdef x
#ifdef y // skip = 1
#else    // skip = 0
#endif   // break out of skipping and parse as endif for #ifdef x
#endif // error: ENDIF without matching IFDEF/IFNDEF
```
This will make an #else only stop skipping when it would have stopped skipping on the next #endif anyway
Demonstration of the fixed behavior
```
// x is undefined
// y can be defined or undefined with neither case causing an error
#ifdef x
#ifdef y // skip = 1
#else    // skip is still 1
#endif   // skip = 0
#endif // break out of skipping and parse as endif for #ifdef x
```

Else in nested ifdefs fixed for new ifdef handling

---

lua/wire/zvm/zvm_data.lua
lua/wire/zvm/zvm_features.lua
lua/wire/zvm/zvm_opcodes.lua

When the IPREC register is at 32 or below, it will now use the bit library and then clamp it to the desired integer precision using a BAND
For demonstrative purposes, the left CPU is using a modified version of the old BSHL with the 30 cycle penalty removed, and the right CPU is using the new BSHR which will have no cycle penalty at 32 bit and below IPREC, both CPUs are set to 32 bit precision.
Both CPUs are at 14MHz, which is 10x the default limit of 1.4MHz
https://github.com/wiremod/wire-cpu/assets/57756830/71824bcb-56a8-4fa4-a545-4473aa6c7c00

Bit operations below 33 bits now use the inbuilt bitwise library

---

lua/autorun/cpu_load.lua
lua/entities/gmod_wire_cpu.lua
lua/entities/gmod_wire_gpu/cl_gpuvm.lua
lua/entities/gmod_wire_gpu/cl_init.lua
lua/entities/gmod_wire_gpu/init.lua
lua/entities/gmod_wire_spu/cl_init.lua
lua/entities/gmod_wire_spu/init.lua
lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_opcodes.lua
lua/wire/client/hlzasm/hc_output.lua
lua/wire/client/hlzasm/hc_syntax.lua
lua/wire/client/hlzasm/hc_tokenizer.lua
lua/wire/client/text_editor/modes/zcpu.lua
lua/wire/cpulib.lua
lua/wire/cpulib_example_extension.lua
lua/wire/stools/cpu.lua
lua/wire/stools/gpu.lua
lua/wire/stools/spu.lua
lua/wire/zvm/zvm_core.lua
lua/wire/zvm/zvm_opcodes.lua

Extends CPULib to allow for addons to add new instructions to a ZVM platform on a per-entity basis, determined by the player's load order at entity creation.
The UI to load and unload extensions is available in the tool menu, clicking on an extension will switch it between the two categories
It will only show the available extensions for said tool, you won't see GPU extensions when looking at the CPU tool for example.
The HLZASM compiler & editor are aware of your currently available extended instructions, and can only highlight or compile them while enabled
(extension is enabled)
(extension is disabled)
Compilation/upload is also affected by the player's load order, so keep in mind if the load order differs between player & ent your code may not work correctly.
See …

CPULib Extension framework

---

lua/entities/gmod_wire_gpu/cl_gpuvm.lua
lua/entities/gmod_wire_spu/cl_spuvm.lua
lua/wire/zvm/zvm_core.lua

Every compiled function from an emitted block is now wrapped in a stripped down environment containing only the necessary libraries, and the VM's contents
Platforms that require extra libraries or outside variables add them to VM.Env to allow the VM to access them

Sandboxes the ZVM

---

lua/wire/cpulib.lua
lua/wire/zvm/zvm_opcodes.lua

Some instructions already have an L prefix for the logical version such as LNEG. Easier to remember and easier to tell it apart from its bitwise counterparts.
OR -> LOR
XOR -> LXOR
AND -> LAND
LNEG -> LNOT

More logical instruction mnemonics

---

lua/entities/gmod_wire_cpu.lua

Stores a reference to the Entity in the VM for the ZCPU
It hadn't occurred to me up until this point that I'm probably going to need this if I want the ZCPU extensions to be able to refer to themselves, like how ZGPU and SPU can.
No baseline functionality is altered, no instructions in the base ZCPU set attempt to access the entity.

ZCPU VM now self-aware like GPU and SPU VMs are

---

lua/wire/zvm/zvm_opcodes.lua

Div checks if the abs of a number is less than 0.000000000001 (as 1e-12), if this is the case it will send interrupt 3 and not modify the registers value
This PR brings the same behavior to modulo, which was just returning math.fmod(op1,op2), preventing setting a register to NaN and potentially causing errors by outputting it or operating on it.

Copy DIV by zero behavior for handling modulo by zero

---

lua/wire/cpulib.lua

When instructions in ZVM are branching, they need to set PrecompileBreak on the VM to end the compilation early, this ends the function and when the compiled block is run, any calls to VM:Jump will set VM.IP and be allowed to take effect, since VM.IP won't change as the block runs.
Uses the CB and UB flags to alter this behavior on a per instruction basis at initial load of extension.
So if you flag your function as being Conditionally Branched or Unconditionally Branched when using ext:InstructionFromLuaFunc your function will be able to call VM:Jump and have it take effect properly.

Extension Lua Instructions w/ flag can now break precompile

---

lua/entities/gmod_wire_cpu.lua
lua/wire/stools/cpu.lua

Adds support to the ZCPU tool for setting an arbitrary(clamped) number of pages for RAM and ROM separately
Technically possible beforehand, as dupe info saved the ram and rom size, not the memory model, so altering it would allow you to have an arbitrary number of bytes for both, this just provides a UI for sanely setting them in a way that respects the paging system.
Capped at 1024 pages(128kb, same as the largest default memory model)
Sliders are shown for ram/rom when the custom ram/rom option is picked and hidden when custom ram/rom
CPU Reporting 3072 bytes of ram (24 pages, same as the slider depicts)
Leaves a small gap when custom ram/rom isn't selected
CPU Reporting 128 bytes of ram(1 page)

Custom RAM/ROM Sizes

---

lua/wire/cpu_default_data_decompressor.lua

Turns out it only worked for me when I had wire-cpu in my addons folder.
This should work on the workshop version too, since it seems to work *this* time without needing to know the addon's folder name.

Fix example paths to use gmod's mounted data_static folder

---

lua/wire/zvm/zvm_opcodes.lua

LOOPB was referencing VM.EBX for its ~= 0 condition and not EBX, the local copy that was modified during *this* call, which meant it was the value before the decrement and not after the decrement.
Documentation of LOOPB was worded the same as LOOPA, LOOPC, LOOP, and LOOPD, which makes me further believe LOOPB's behavior was in error.
Also technically boosts performance of LOOPB,, because it's not indexing EBX from VM twice anymore and is now properly using the local version, same as the other LOOP instructions are.

LOOPB now ends on 0 instead of -1 like other loops

---

lua/wire/cpulib.lua

Uses the github pages provided in the wiremod/miscellanious section, instead of "http://wiki.wiremod.com/wiki/Category:ZCPU_Handbook" which redirects to a 404.
When [this PR](https://github.com/wiremod/Miscellaneous/pull/12) passes, clicking on ZGPU and ZSPU will jump to the relevant section on open.

Updated link to docs, jumps to relevant section per tool.

---

lua/wire/zvm/zvm_data.lua

For R0-R31 being used as a register, previously it would do an interrupt check as if it were a memory access, this will no longer be the case and R0-R31 access (as registers, not using them for memory access) will no longer use interrupt checks, bringing them to an equal performance as using the regular(EAX, EBX, etc.) registers.

Stop marking R0-R31 as needing interrupt checks

---

lua/entities/gmod_wire_gpu/cl_gpuvm.lua
lua/entities/gmod_wire_spu/cl_spuvm.lua
lua/wire/cpulib.lua
lua/wire/zvm/zvm_core.lua
lua/wire/zvm/zvm_data.lua
lua/wire/zvm/zvm_features.lua
lua/wire/zvm/zvm_opcodes.lua

Now upon executing a privileged instruction without being of the right runlevel, the interrupt will pass the privileged instruction's operands into PreqOperand1 and PreqOperand2, and certain instructions that needed to write to an operand can now retrieve a return value from PreqReturn.
Internal registers added:
71 = PreqOperand1 | in MOV R0,R1, this would hold R0
72 = PreqOperand2 | in MOV R0,R1, this would hold R1
73 = PreqReturn | The number to be returned, if the instruction needs one.
74 = PreqHandled | Whether or not this request was handled, is set to -1 on entering interrupt, if set to 1 then PreqReturn will be used if needed. As long as it's nonzero the privileged instruction is considered handled on return
Opcodes that will use PreqReturn:
CPUGET
RD
GMAP (which I've also fixed …

Privileged instructions can now be proxied by interrupt 13

---

lua/wire/zvm/zvm_features.lua

MEMRQ = 5 just takes Address and Value from MEMADDR and LADD, before performing the write itself.
If the user wanted to cancel a write request or perform another operation on write instead, they would still end up having the operation perform, and a byte written to the trapped page by default(the write is non-negotiable, it HAS to go somewhere, and preventing a value changing from write requires hacky workarounds).
MEMRQ = 6, which is new, will outright cancel a write request instead of just changing the address and value, allowing you to prevent any write happening at all without having to do a workaround.

Use MEMRQ = 6 to signify interrupt handled write

---

lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_preprocess.lua
lua/wire/client/text_editor/modes/zcpu.lua
lua/wire/cpulib.lua
lua/wire/stools/cpu.lua
lua/wire/stools/gpu.lua
lua/wire/stools/spu.lua

Provides support for the upcoming changes in https://github.com/wiremod/wire/pull/3127 by porting some of the functionality of the original E2Helper implementation for ZCPU here.
The changes allow loaded extensions to display their instructions properly in E2Helper thanks to being able to update descriptions and items at CPULib's will.
Backwards compatible with older versions of wiremod before this change, letting the hardcoded E2Helper & Text Editor control us, but the new version of wiremod won't be able to support versions of ZCPU before this, sadly.
(this is what it'll look like for an older zcpu version on new wiremod, still compiles when you click but no syntax highlighting or helper, technically functional)

E2Helper & Text Editor Module Support

---

lua/entities/gmod_wire_gpu/cl_gpuvm.lua
lua/wire/cpulib.lua

Implements the DARRAY instruction
Though the only documentation of its existence was a commented out CPULIB entry stating that it took VEC2F, and STRUCT as arguments, and the description stating "Draw an array of pixels", this adds it in a functional state.
VEC2F is position to start draw
STRUCT is a pointer to a struct made up of:
Resolution X
Resolution Y
Pixel Width
Pixel Height
Color Mode (this currently has the same set of color modes as the digital screen)
Pointer to color buffer
Uses a quota interrupt like MCOPY to allow a buffer of any size to be drawn.
Color modes available:
0 = RGBXXX (1 cell per pixel)
1 = R G B (3 cells per pixel)
2 = 24 Bit RGB / True Color Mode (1 cell per pixel)
3 = RRRGGGBBB / Digit packed RGB mode (1 cell per pixel)
4 = Mono color / Grayscale (1 cell per …

DARRAY Instruction implemented

---

lua/wire/client/hlzasm/hc_compiler.lua
lua/wire/client/hlzasm/hc_syntax.lua
lua/wire/client/text_editor/modes/zcpu.lua

Makes the code editor more unified and better to look at rather than some types being colored and your structs being the same color as regular text.
The keywords are added during compile and will change once you type. When you compile a script that does not have those structs they will be removed from the list to highlight.

Add syntax highlighting to structs to be like other types.

---

lua/wire/zvm/zvm_opcodes.lua

The segment argument for the %d was in the string.gsub rather than string.format. I've tested it and it does work.
**Error**
**Code**
**Here is it successfully writing to my DSP (addon) memory (a wav file)**

Fix LEA instruction

---

lua/wire/cpulib.lua

Fix a issue with the breakpoint highlighting not getting removed when breakpoint is removed, issue with the current debugger position highlighting not getting removed when detaching, and a error trying to open the ZCPU documentation from the tool

Fix line highlighting bug and Fix opening ZCPU documentation
